# Generated by Django 3.2.11 on 2022-11-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=128)),
                ('envs', models.CharField(max_length=128)),
                ('command', models.CharField(max_length=128)),
            ],
        ),
    ]
